### ISSUE TITLE
客户端

### ISSUE THREAD

**Issue by mofrom** [gotoeasy/glogcenter#1]
客户端需要怎么配置才能采集日志？
比如nginx日志。

**Comment by gotoeasy** [comment]
系统众多无法都编写客户端进行适配，常见的思路就是日志文件收集，
然而，日志文件的收集也是要根据文件格式进行解析，理想的解析还得支持配置或简单的编写脚本来灵活实现。

简而言之，日志文件的解析收集要做得全做得好，需要考虑的东西很多，并不那么简单，
目前这方面的需求还不强烈，暂时还没计划

**Comment by plly0090** [comment]
不支持直接采集日志文件么

**Comment by gotoeasy** [comment]
> 不支持直接采集日志文件么

你说的这个是类似 filebeat 的功能
暂时没计划做这个轮子，原因同上

**Comment by bytew021** [comment]
能直接用filebeat 采集在这边接收吗~

**Comment by gotoeasy** [comment]
> 能直接用filebeat 采集在这边接收吗~

当然，也需要折腾下filebeat 采集

　

当前`0.8.5`版本GLC支持http接口和RabbitMq接口两种方式接收日志，并不限制采集器采集方式，比如命令行也是可以
```
curl -d '{"system":"demo", "date":"20230101 01:02:03.456","text":"demo log text"}' http://127.0.0.1:8080/glc/v1/log/add
```
