### ISSUE TITLE
关于单应用多实例使用问题

### ISSUE THREAD

**Issue by lovcomputer** [gotoeasy/glogcenter#10]
大佬的日志确实使用起来很方便，目前使用的时候遇到各问题，对于微服务状态下，单个应用，启动了多个实例，目前的日志平台只有按照分类来进行区分(并且分类没有默认的提示，得手动输入),导致多个实例的日志全部混在一起了

**Comment by gotoeasy** [comment]
这个本意是想节省资源，所以多系统混用共用一个日志中心
另一方面，微服务多应用相互调用，假设不用应用使用不同的分类名称，这时也是有需要同时查询多个分类的

不同系统的检索筛选条件，理应作成下拉选项，或是也支持多选，有待后续版本优化

----------------------
有比较普遍或强烈的应用场景或需求，欢迎提出

**Comment by lovcomputer** [comment]
没错，同一个应用多个实例，分类名一般是一样的，现在会出现的问题就是如果分类名相同的多实例日志都放在一起，如果有的实例有报错日志，有的实例没有，那么仅通过日志中心是没法区分那个实例有问题，还得搭配应用监控中心来确认；我看同类的应用中，有的是把ip和实例进行绑定了

**Comment by gotoeasy** [comment]
> 没错，同一个应用多个实例，分类名一般是一样的，现在会出现的问题就是如果分类名相同的多实例日志都放在一起，如果有的实例有报错日志，有的实例没有，那么仅通过日志中心是没法区分那个实例有问题，还得搭配应用监控中心来确认；我看同类的应用中，有的是把ip和实例进行绑定了

理解你的意思了，当前版本确实是有这个问题，内部只是预留了字段，包括按traceId跟踪查看日志等，暂时还没有这样去做
因为页面展示空间有限，需要页面也能同步可以设定指定字段是否显示，改动量较大

这部分是预留待实现功能，后续版本考虑实现

**Comment by gotoeasy** [comment]
0.10.0 版本已实现，主机名或主机IP的展示可页面上自定义显示列
glc-logback-appender:0.10.0 需要等公共仓库生效
