### ISSUE TITLE
搜索不到日志内容

### ISSUE THREAD

**Issue by gwself** [gotoeasy/glogcenter#11]
![image](https://github.com/gotoeasy/glogcenter/assets/20888271/383880d8-bb4e-4652-912c-791b427e0aa9)

通过红框内的字符串搜不出来

**Comment by gwself** [comment]
过了好一会才搜索出来的

**Comment by gotoeasy** [comment]
那就是建索引的时间差原因了，设计如此
GLC本身占用的资源少，看看是不是其他什么占用机器资源了
