### ISSUE TITLE
搜索不出来

### ISSUE THREAD

**Issue by gwself** [gotoeasy/glogcenter#12]
![image](https://github.com/gotoeasy/glogcenter/assets/20888271/f4fb05a3-201a-408d-ab44-f6276bdc1cb6)
通过搜Exception 只能搜索到精确匹配的

**Comment by gotoeasy** [comment]
或是Exception 的日志就1条？
或是索引还没建好（优先响应保存日志，空闲时间才建索引）

**Comment by gotoeasy** [comment]
另外注意是关键词全文检索，不是模糊检索，理解上不要出偏差
比如用 Exception 是查不出 RuntimeException 的，除非日志中有 Exception 这个单词
（并且是限于日志的第一行，像上面的异常堆栈内容就不是检索对象）
