### ISSUE TITLE
使用docker部署glc，后续升级如何迁移数据

### ISSUE THREAD

**Issue by liwenchao1984** [gotoeasy/glogcenter#13]
请题，如果glc后续升级。请问如何迁移数据。

**Comment by gotoeasy** [comment]
目前建议用新版0.10.0，升级点还是较多的
0.8.*版本开始已经有注意到数据兼容问题，升级会尽量考虑数据兼容，不过倒也没有特意做这个测试

在数据兼容的情况下，直接升级程序是能正常使用原数据的

**Comment by gotoeasy** [comment]
日志数据类似json形式存储，理论上能兼容没有影响
