### ISSUE TITLE
建议在数据库添加一个level字段，方便按DEUBG、INFO等不同级别查询

### ISSUE THREAD

**Issue by liwenchao1984** [gotoeasy/glogcenter#14]
![image](https://github.com/gotoeasy/glogcenter/assets/38348431/b0757fb3-e34d-4b4b-b240-2f931f177b52)
在Appender中，从event.getLevel().levelStr可以拿到日志级别。

GlcHttpJsonAppender 的submitToGlogCenter()方法
1、添加Stirng level参数
2、http请求添加level传参

GlcAmqpAppender 的sendToRabbitMQ()方法添加Stirng level参数
1、添加Stirng level参数
2、http请求添加level传参

由于不会go语法，不知道go那边和数据库怎么接收处理，帮不上忙。
仅自己的一点小小建议。

**Comment by gotoeasy** [comment]
日志级别筛选还没遇到非常严格的要求，比如像搜info不允许出现error，没有这种严格要求的情况下，多关键字查询就好，比如【info key1 key2】诸如此类

不过，可以考虑加上这个严格的筛选条件，符合一定的使用习惯
下个版本见
