### ISSUE TITLE
搜索不到

### ISSUE THREAD

**Issue by JerryChenn07** [gotoeasy/glogcenter#15]
启动命令 `docker run -d -p 9090:8080 -v ./logs:/glogcenter gotoeasy/glc`

```
./logs 下面的有a、b、c....多个目录，目录结构如下
./logs/a/log/root.log
./logs/b/log/root.log
./logs/c/log/root.log
```
里面有几十mb的日志，为啥我搜不到呢

日志仓也能找到
![image](https://github.com/gotoeasy/glogcenter/assets/32920461/c327373b-aeb4-425b-b898-854cf5595791)

但是我去搜索，没任何反应，有点晕

**Comment by gotoeasy** [comment]
下面的图是应有的样子

1）必要时当前最新版 0.10.1，加上版本号确保运行的是你要的版本
2）挂载的本地目录不要太随意了（应挂载到一个新目录），混杂着其他目录被当做日志仓目录了，这种目录肯定没有日志数据。日志数量、已建索引数量，这两列都是空白，也说明了问题
3）只想实验试试看效果的话，可以再简单点不必挂载目录，同时也可以排查是不是挂载目录原因影响

![image](https://github.com/gotoeasy/glogcenter/assets/9602197/607d40ad-20a1-4414-bd1b-6c78e3d35765)
![image](https://github.com/gotoeasy/glogcenter/assets/9602197/21bd6eb9-e82c-4faa-a870-e0ae4f53d2b8)

**Comment by JerryChenn07** [comment]
使用了0.10.1镜像，没有磁盘映射，只是run了一下，进容器内部，手动创建了一个文件和两个日志并手动写入一些日志内容，如图web-api/001.log web-api/002.log
![image](https://github.com/gotoeasy/glogcenter/assets/32920461/b95d446d-d041-4743-a530-8584f50640e1)
依然搜不到
![image](https://github.com/gotoeasy/glogcenter/assets/32920461/43f10cf8-111b-4ae8-9a14-a68a504e1ad5)

**Comment by gotoeasy** [comment]
这是什么用法？

这个是日志中心，接收来自各处的经接口传入的日志，然后可以检索，不是你这样自己存放日志文件的用法

java项目通常都可以比较方便的接入
服务接口是rest方式，有特别需求的话也可以直接对接接口传入日志
看下首页的说明

**Comment by JerryChenn07** [comment]
好吧 我还以为直接可以读取指定路径下的文件呢
