### ISSUE TITLE
bug: v0.10.1版本，按日志级别查询有误

### ISSUE THREAD

**Issue by liwenchao1984** [gotoeasy/glogcenter#16]
我在代码中按四个级别打印了日志：
![image](https://github.com/gotoeasy/glogcenter/assets/38348431/a341b3b7-c302-4943-b3a3-b68ab13334e9)

GlcHttpJsonAppender和GlcAmqpAppender都能成功发送、保存日志，

bug:
 当使用GlcHttpJsonAppender记录器，搜索不到warn级别日志。（debug、info、error的可以搜索到）
 当使得GlcAmqpAppender记录器，所有级别都搜索不了。

**Comment by gotoeasy** [comment]
够仔细
0.10.2 已修复

**Comment by liwenchao1984** [comment]
已复测。  GlcAmqpAppender版能正常按各个级别准确查询。

但是GlcHttpJsonAppender版，仍然不能查到WARN级别。
另外，pom依赖没有升级到0.10.2
```java
		<dependency>
		    <groupId>top.gotoeasy</groupId>
		    <artifactId>glc-logback-appender</artifactId>
		    <version>0.10.1</version>
		</dependency>	
```

**Comment by gotoeasy** [comment]
![image](https://github.com/gotoeasy/glogcenter/assets/9602197/040c4866-1ba9-4bc8-822d-89132da3854a)

不应该啊，传的条件已经修复成了warn，原来是warning所以错了，我这也确实能查出来

【glc-logback-appender】没有修改可以用0.10.1版本，对应的新版本号发布到公共仓库需要个过程

**Comment by gotoeasy** [comment]
【glc-logback-appender】0.10.2版本已发布，和0.10.1一样没有修改，仅版本号同步
