### ISSUE TITLE
功能建议：建议添加traceId、客户端IP查询条件

### ISSUE THREAD

**Issue by liwenchao1984** [gotoeasy/glogcenter#17]
up主，可以把“traceId、客户端IP”放到查询条件中不，   方便跟踪恶意请求。

**Comment by gotoeasy** [comment]
除日志仓和时间以外，其他所有条件都是关键词全文检索，可在主页面直接输入条件进行查询，多个关键词时，用空格或标点符号之类隔开就好，比如输入【关键词1  关键词2  关键词3】，日志仓默认当天，要切换时需选定，时间由于不是关键词也所以需要手动选择

单独字段条件的目的是精确的过滤，比如输入指定系统名，目的是完全排除其他系统的查询结果

traceId的重复可能性极低，直接查询就已经几乎精确，没必要再单独作为字段条件输入
客户端ip也是类似，直接查应该就能满足需要了
