### ISSUE TITLE
在筛选条件命中后，只能显示100条，无法继续向下滚动显示更多

### ISSUE THREAD

**Issue by tgabc** [gotoeasy/glogcenter#19]
![image](https://github.com/gotoeasy/glogcenter/assets/49581225/773cbbaa-ced2-488e-af5e-f40cb4d45668)
日志总量 2735732 条，当前条件最多匹配 284553 条，正展示前 100 条。然后无法操作去展示超过100条的数据。
使用docker镜像版本部署： gotoeasy/glc:0.10.2

**Comment by gotoeasy** [comment]
鼠标滚轮滚动到底，或者拖动滚动条到底，这时会触发查询下100条
滚动条接触到底部就会触发查询，可打开浏览器控制台，上下多次碰撞，看网络请求是不是有不断的新的请求出现

这是一直以来的固有操作设计，没有修改过，不应该有问题

**Comment by tgabc** [comment]
感谢提示：经过尝试，鼠标滚轮滚动到底，或者拖动滚动条到底，在我原来电脑浏览器上并未成功触发，控制台也没有产生请求，但是换了一台其他人的电脑就是正常的。这属于我本地环境问题，并非glogcenter的问题。暂时未查明关键的区别在哪，计划重装浏览器进行进一步尝试。

**Comment by gotoeasy** [comment]
哦，网页端用的是vue，仅支持主流浏览器
