### ISSUE TITLE
请问是否存在特殊字符过滤？

### ISSUE THREAD

**Issue by daojiAnime** [gotoeasy/glogcenter#2]
![image](https://user-images.githubusercontent.com/30306060/220061819-156770d9-e631-4647-a393-307e7840a2ad.png)
我正在收集Python程序的日志信息，这里我捕获了堆栈信息，在控制台显示如上图。我在发起请求之前检查了请求信息，确实是带有堆栈信息，但是部分信息在前端显示的时候是空白的。如下图所示
![image](https://user-images.githubusercontent.com/30306060/220062392-1cb2fec8-c24a-4d70-8423-960c48bc70f7.png)
![image](https://user-images.githubusercontent.com/30306060/220062518-d09f62d5-1ae9-4a89-b8e9-680d8686a29b.png)

**Comment by daojiAnime** [comment]
我忽然想起来本项目的前端是vue实现的，可能使用v-html将这个当作标签渲染了。查看页面元素确实是如此，
![image](https://user-images.githubusercontent.com/30306060/220065578-903c42e7-1803-4eec-9e84-8896105bdc38.png)

**Comment by gotoeasy** [comment]
很好，所言极是！

`0.8.7`已修复此问题
