### ISSUE TITLE
如何命中时间戳索引完成日志检索？

### ISSUE THREAD

**Issue by tgabc** [gotoeasy/glogcenter#20]
![image](https://github.com/gotoeasy/glogcenter/assets/49581225/be9f50da-57aa-4612-ba16-da98ec67dc6d)
![image](https://github.com/gotoeasy/glogcenter/assets/49581225/3366d27f-0f6f-45be-9ab9-4d5cd0626f9d)
![image](https://github.com/gotoeasy/glogcenter/assets/49581225/4e5f8fd1-049d-457f-8d9e-06b6e252b243)

如图所示，尝试了多种时间字段的格式的输入，均发现无法通过时间日期字段检索出日志，只能通过系统名称检索。另外通过“近10分钟”选项检索出来的也不符合时间日期的筛选：
```
# 示例中发送测试数据的参考脚本中的时间格式
curl -X POST -d '{"system":"demo", "date":"20230816 06:44:54.456,"text":"demo log text"}' \
  -H "Content-Type:application/json" http://127.0.0.1:8080/glc/v1/log/add

# filebeat中生成的时间格式
curl -X POST -d '{
  "@timestamp": "2023-08-16T06:44:54.389Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.9.0"
  },
  "system": "iot-sync-local-deployment",
  "date": "2023-08-16T06:44:54.389Z",
  "message": "2023-08-16 06:44:54.386 DEBUG 1 --- [p-nio-80-exec-4] o.s.web.servlet.DispatcherServlet        : Completed 200 OK",
  "text": "2023-08-16 06:44:54.386 DEBUG 1 --- [p-nio-80-exec-4] o.s.web.servlet.DispatcherServlet        : Completed 200 OK"
}' \
  -H "Content-Type:application/json" http://127.0.0.1:8080/glc/v1/log/add
```
是否是时间日期字段的填写问题？
docker镜像版本：gotoeasy/glc:0.10.2

**Comment by gotoeasy** [comment]
你提了个好问题，看起来是有些场景会出BUG，先说下目前的处理方式

目前时间字段实际是按字符串处理，我一直用的时间格式样子是  【2023-08-16 18:06:52.049】，这种格式检索正常。
当使用时间范围条件时，比如 【2023-08-16 18:00:00 ~ 2023-08-16 19:00:00】
这时后端实际是按【2023-08-16 18:00:00.000 ~ 2023-08-16 19:00:00.999】这个范围进行字符串比较后查取结果

你用的时间格式不是  【2023-08-16 18:06:52.049】这种格式，应该是这个原因导致比较结果不对

【解决办法】
1、修改成上面的默认时间格式，但旧数据应该是仍旧查不出
2、等待下一版本改善，可能旧数据仍旧会查不出（因为是按字符串存储及索引）

**Comment by tgabc** [comment]
感谢回复，我先尝试修改filebeat默认输出的时间格式去适配glc。如果搞定的话，我可以在后续回复中贴出我的filebeat配置以供他人参考

**Comment by tgabc** [comment]
filebeat 8.0.9版本参考配置，用于单机容器日志收集（output.http插件编译自https://github.com/raboof/beats-output-http）：
```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
processors:
  - add_docker_metadata: ~
  - copy_fields:
      fields:
        - from: message
          to: text
        - from: container.name
          to: system
      fail_on_error: false
      ignore_missing: true
  - script:
      lang: javascript
      id: timestamp_filter
      tag: enable
      source: >
        function process(event) {
            var str=event.Get("@timestamp").toString();
            //event.Put('wwwwwy',typeof str);
            var time1=str.split(" ").slice(0,2).join(' ').split("").slice(0,23).join('');
            event.Put("date",time1);
        }
  - drop_fields:
      fields: ["stream","input","agent","ecs","log","host","docker","container"]
      ignore_missing: false
output.http:
   hosts: ["http://glc:8080/glc/v1/log/add"]
   protocol: "http"
   max_retries: 3
   timeout: 90
   format: "json_lines"
   content_type: "application/json"
   headers:
     glc: 'Abqm123'
   tls:
     enabled: false
```

生成出来的输出如下：
···
{
  "@timestamp": "2023-08-18T01:04:14.376Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.9.0"
  },
  "message": "{",
  "text": "{",
  "wwwwwy": "2023-08-18 01:04:14.37642212 +0000 UTC",
  "date": "2023-08-18 01:04:14.376",
  "system": "glc-filebeat"
}
···
