### ISSUE TITLE
搜索可以支持正则表达式查询吗？

### ISSUE THREAD

**Issue by gwself** [gotoeasy/glogcenter#22]
新特性

**Comment by gotoeasy** [comment]
呵呵，这个。。。基本不会有
亿级数据量，用正则查询，性能难以设想啊

**Comment by gwself** [comment]
类似ELK 支持的正则查询

**Comment by gotoeasy** [comment]
> 类似ELK 支持的正则查询

嗯，ELK中如果用不好正则，很容易搞崩服务器

**Comment by gotoeasy** [comment]
正则查询或通配符查询，我几乎不用，这些使用场景我感觉挺少有的
还有更花哨的用自然语言查询，也即是语义检索，那性能也是非常的好

我觉得针对日志查询场景，这些还是不大贴切，目前暂不考虑支持

**Comment by gwself** [comment]
考虑支持类似于Kibana Alert  的小功能吗，例如：创建一个告警单位时间内error 占比一个阈值，发送邮件的功能

**Comment by gwself** [comment]
> 考虑支持类似于Kibana Alert 的小功能吗，例如：创建一个告警单5分钟内error 占比达到一个阈值，发送邮件的功能

**Comment by gotoeasy** [comment]
> > 考虑支持类似于Kibana Alert 的小功能吗，例如：创建一个告警单5分钟内error 占比达到一个阈值，发送邮件的功能

这个可以有

日志的分析、告警，都是以后要加入的内容
主要是看怎样简洁的加入这些功能
