### ISSUE TITLE
支持下载功能

### ISSUE THREAD

**Issue by jszls65** [gotoeasy/glogcenter#23]
因为服务器的磁盘空间一般不会存很长时间且很大的日志文件, 我们的服务器一般只保留7天的日志数据, 
为了避免日志过期, 在检索到某些有问题的日志, 是否可以支持下载到本地, 以后慢慢处理呢? 

我的想法是第一列前面加多选框, 可以让用户自己选择需要下载的行, 支持一键勾选当前页所有行 , 可以避免一次下载数据量太大把服务搞崩, 可以限制一次最多选择500条, 如果一行不是很长的话, 500条应该很小, 可以直接导出, 如果很大的话, 也可以是zip包.

**Comment by gotoeasy** [comment]
页面上勾选指定的日志保存为文件，这个可以有

不过日志很多都有换行内容，导出什么形式好呢，csv好像不大合适，json字符串好像又比较粗鲁
可以出出点子，呵呵

**Comment by gotoeasy** [comment]
gotoeasy/glc:0.11.2  已添加下载按钮，内容是当前检索结果，格式txt按自然换行，内容按页面当前显示列输出

**Comment by jszls65** [comment]
第一版 txt就可以, 应该能满足90%的场景.  没必要csv

**Comment by gotoeasy** [comment]
就这样吧，页面最多显示5000条，没多大，文本格式也还合适，就这样了
