### ISSUE TITLE
带有换行符的字符串无法搜索

### ISSUE THREAD

**Issue by lchjczw** [gotoeasy/glogcenter#24]
<img width="712" alt="image" src="https://github.com/gotoeasy/glogcenter/assets/12480676/349087a7-27ed-4ca5-9115-5af9300da3c3">
<img width="1236" alt="image" src="https://github.com/gotoeasy/glogcenter/assets/12480676/7dca1981-8240-44ac-aaaa-c856d68334af">

第一张图是我不带条件搜索出来的结果,里面有带有换行符的日志内容
第二张图是我加了条件,带有换行符的结果没有搜索出来
用最新版本的docker部署

**Comment by gotoeasy** [comment]
看你的截图，日志是json字符串（json字符串很可能会有换行），这种用法出乎我的意料


日志列是通常的日志内容，比如常见的java日志，一般单行，有异常堆栈时是多行
所以目前的设计是，日志列仅对第一行作索引检索，换行的部分是忽略的，因此也就出现了你这种情况


日志列的全部行都作为索引及检索对象，也许会稍微多用点点空间，但倒也是合理需求
下一版本增加多行检索的配置开关，支持类似你这种场景

**Comment by gotoeasy** [comment]
0.12.0 版本已增加支持，配置环境变量GLC_SEARCH_MULIT_LINE为true即可。

不过要注意到，历史数据还是旧的索引，仍旧是不支持多行检索的

**Comment by lchjczw** [comment]
感谢
