### ISSUE TITLE
日志只能显示前一百条

### ISSUE THREAD

**Issue by nirui-github** [gotoeasy/glogcenter#25]
日志只能显示前一百条，停止自动查询，往下拉仍然无法加载下面的日志，dockers方式部署的。还有可以按照时间倒序排查看嘛，比如倒序

![1700797813711](https://github.com/gotoeasy/glogcenter/assets/53802411/eb66d8b8-6bcd-4c90-b281-98a1ad28a7d3)

**Comment by gotoeasy** [comment]
1、滚动或拖动滚动条到底部，是会触发继续检索的，你可以打开浏览器控制台看是否触发了新的网络请求，这是一直在用的基本功能，不该会有问题

2、日志按时间升序查看，比如最旧的在上新的在下？恐怕会显得很不自然。最多的场景是查最近的日志，比如每次查出新日志，如果倒着查，每次都是查出不会变化的最旧日志在前面，意义不大

**Comment by nirui-github** [comment]
拖到最下面没有出发最新请求，我是只有docker部署的
docker run -d -p 2122:8080  \
 -e  GLC_SAVE_DAYS=30  \
 -e  GLC_ENABLE_LOGIN=true  \
 -e  GLC_USERNAME=admin  \
 -e  GLC_PASSWORD=admin@123  \
 -e  GLC_ENABLE_CORS=true  \
 -v /root/glc:/glogcenter  \
 --name glogcenter  \
gotoeasy/glc

**Comment by nirui-github** [comment]
不好意思啊，我这边操作问题，是需要把自动查询开启才可以刷新

**Comment by nirui-github** [comment]
不行，自动查询开启还是获取最新的100条，无法获取100到200条
