### ISSUE TITLE
大佬，问下什么时候支持可以收集本地日志文件？

### ISSUE THREAD

**Issue by neowj** [gotoeasy/glogcenter#27]
线上使用ELK，备份的日志就是日志文件，所以想用这个试试！

**Comment by gotoeasy** [comment]
https://github.com/gotoeasy/glogcenter/issues/20

这里有热心朋友写的例子

**Comment by gotoeasy** [comment]
`0.17.0`版本开始，支持基于`fluentd` 收集各种日志，包括文件
