### ISSUE TITLE
一个关于版本号检测的建议

### ISSUE THREAD

**Issue by uouuou** [gotoeasy/glogcenter#28]
个人认为在glcui库里面内置版本检测提示稍微有点不合适，毕竟您的网站有时候会崩溃，而且有收集用户信息的链路了，不是很好，还是建议做成可选项或者优化掉这部分，个人拙见

**Comment by gotoeasy** [comment]
1，希望版本更新时，有个比较适当的提示，提示也是可以选择不再提示（如果网络等原因检查不到新版本号，不应报错）
2，希望知道大体有多少人数在使用（docker镜像仅下载次数统计，并不适用），当然，源码开放的，不可能会去收集用户信息
3，希望上面功能不会被轻易的修改剔除掉，所以放进glcui库里增加点难度

若有更好的办法欢迎提出

**Comment by uouuou** [comment]
> 1，希望版本更新时，有个比较适当的提示，提示也是可以选择不再提示（如果网络等原因检查不到新版本号，不应报错） 2，希望知道大体有多少人数在使用（docker镜像仅下载次数统计，并不适用），当然，源码开放的，不可能会去收集用户信息 3，希望上面功能不会被轻易的修改剔除掉，所以放进glcui库里增加点难度
> 
> 若有更好的办法欢迎提出

 如果是这样的话我建议更新一下@gotoeasy/glcui这个库，这个库没更新好像，会导致用户列表那个部分加载不到

毕竟也有可能需要一些些的定制化开发的，比如多一些信息收集什么的，docker部署说实话也不是所有用户都希望的，个人见解哈
