### ISSUE TITLE
一个小小的建议关于go的cmn包

### ISSUE THREAD

**Issue by uouuou** [gotoeasy/glogcenter#29]
因为cmn包里面的一些方法比如分词等会带词典，对打包大小有很大影响，建议独立抽离出glc的方法

**Comment by gotoeasy** [comment]
就是非glc目的时使用cmn会影响打包大小是吧？
这个问题确实会有，现在得cmn有点大杂烩的样子，并不是glc专用的目的，打包后可能会多约20M的大小

暂时还没精力做这个优化，以后看情况吧
