### ISSUE TITLE
关于镜像封装的疑问

### ISSUE THREAD

**Issue by daojiAnime** [gotoeasy/glogcenter#3]
![image](https://user-images.githubusercontent.com/30306060/220230787-564aaae5-9596-4ecd-b9c5-fb619198f23b.png)
![image](https://user-images.githubusercontent.com/30306060/220231576-24ad8817-d5e5-4201-9953-9ae06d9ccb83.png)

因为电脑重启，我昨天测试的容器已经停止了。重启的时候启动的pid 1不是编译后的可执行文件。我上hub.docker.com查看了一下作者的镜像构建，发现了前面构建了一层`CMD ["/bin/sh"]`，虽然`ENTRYPOINT` 会在镜像初始化时覆盖cmd指令，但是重启的时候会以`pid 1`的`/bin/sh`启动。
如果我没理解错的话，这一层应该是多余的，非常感谢作者大大开源此项目，期待后续检索和字段功能的优化。

**Comment by gotoeasy** [comment]
是程序命令行参数问题，docker restart情景欠考虑

0.8.7版本的docker镜像已更新发布，更新拉取新镜像可以解决

**Comment by gotoeasy** [comment]
目前主要功能还处于满足自用阶段，欢迎提功能性等各种优化建议

**Comment by daojiAnime** [comment]
👍
