### ISSUE TITLE
很好用，有没有计划支持kafka

### ISSUE THREAD

**Issue by ddyblackhat** [gotoeasy/glogcenter#30]

**Comment by gotoeasy** [comment]
本意是节省服务器资源，用上`kafka`的话资源又上去了，考虑到日志量可能突发巨大，目前是支持`rabbitMq`缓冲下

若有瓶颈顾虑，与其加中间件，不如先尝试把资源配给日志服务器或许更划算（主要是CPU和高速磁盘），若仍旧有难满足的声音（那量级得有多大啊），再考虑支持`kafka`
