### ISSUE TITLE
以非docker的方式，本地打包到linux环境，无法运行

### ISSUE THREAD

**Issue by tianhuo3652** [gotoeasy/glogcenter#31]
作者大大，请问一下，本地打包成linux环境运行包，打包过程无任何报错，在linux启动 运行包，项目无法启动，无任何报错信息，
请问是有什么需要额外配置的吗？
打包命令：
go build -o glc main.go

环境配置：
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\AppData\Local\go-build
set GOENV=C:\Users\AppData\Roaming\go\env
set GOEXE=
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\Java\GoTools\GoPath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=linux
set GOPATH=D:\Java\GoTools\GoPath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\AppData\Local\Temp\go-build810017971=/tmp/go-build -gno-record-gcc-switches

**Comment by gotoeasy** [comment]
未曾做过docker以外方式的测试，也没有太多时间，恐怕得自己调了

**Comment by tianhuo3652** [comment]
好的，谢谢您的回复
