### ISSUE TITLE
有用户登录的时候，权限系统不生效

### ISSUE THREAD

**Issue by jonfoo86** [gotoeasy/glogcenter#32]
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/1a48af52-9841-4bcb-91e0-53daf80e5c9e)
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/22b6ace4-dd2a-449e-ba4e-922d3044cc03)

这个权限系统不生效

**Comment by gotoeasy** [comment]
cpp1用户是否管理员？（管理员有全部权限）

**Comment by jonfoo86** [comment]
谢谢回复，  cpp1不是管理员  管理员是admin

**Comment by jonfoo86** [comment]
管理员我测试发现 并不会体现在用户列表里面， 我上面的列表就有体现cpp1

**Comment by gotoeasy** [comment]
> 管理员我测试发现 并不会体现在用户列表里面， 我上面的列表就有体现cpp1

管理员是不会出现在用户列表，用户管理仅管理员能操作，没必要把自己显示出来

**Comment by gotoeasy** [comment]
我试下来并没有出现你说的这种权限混乱问题，后端每次检索都有检查过滤处理

如果仍旧有问题，请详细留出操作过程

**Comment by jonfoo86** [comment]
我测试下来 
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/2980b8f9-57f0-4a67-9bc0-00584c48503f)

这种设置多个权限的账户会出现那种混乱的问题，如果我只设置一个cpp1 就没有这个问题，


===========================================================

步骤就是：
1， docker 起了一个最新的镜像（开启登录，不映射系统盘 ）

![image](https://github.com/gotoeasy/glogcenter/assets/17876826/6114c813-7e87-4d8b-8d94-bdcca9172e18)

2，admin登录，添加账户cpp1,给cpp1授权 cpp1,eshadow     ，添加账户cpp2 给cpp2添加授权cpp2

3,  生成cpp2 日志 ，生成cpp1日志

4，登录cpp1 ，cpp1权限混乱

5.， 登录cpp2 ， cpp2权限正常

**Comment by gotoeasy** [comment]
匪夷所思，我又试了一遍，没发现问题

![1710939614577(1)](https://github.com/gotoeasy/glogcenter/assets/9602197/9cbd5684-a0d2-4602-b506-9b42c9625ce5)

![Uploading image.png…]()

![image](https://github.com/gotoeasy/glogcenter/assets/9602197/c6e46eef-3eed-43c8-977e-f110816e2318)

![image](https://github.com/gotoeasy/glogcenter/assets/9602197/6217fe7e-74d1-48f5-abb0-b23cbab8bd39)

**Comment by jonfoo86** [comment]
> 匪夷所思，我又试了一遍，没发现问题
> 
> ![1710939614577(1)](https://private-user-images.githubusercontent.com/9602197/314513646-9cbd5684-a0d2-4602-b506-9b42c9625ce5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODkzNzMsIm5iZiI6MTcxMDk4OTA3MywicGF0aCI6Ii85NjAyMTk3LzMxNDUxMzY0Ni05Y2JkNTY4NC1hMGQyLTQ2MDItYjUwNi05YjQyYzk2MjVjZTUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDI0NDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU2MjgzNTZkMTNjZGQ3ZGEzYmIxY2M0ZDYwMmMwN2QwNzg3ZTQxODRlM2ZjZTI5MzNiMmIzZDM3ZmNhNTdlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OfawI8fTcI9dCoZ2EwEabLAOaqVGNOyPZFLJgRCg-0k)
> 
> ![image](https://private-user-images.githubusercontent.com/9602197/314515313-ff93bc4f-d758-4d97-b85a-c3b33492e1ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODkzNzMsIm5iZiI6MTcxMDk4OTA3MywicGF0aCI6Ii85NjAyMTk3LzMxNDUxNTMxMy1mZjkzYmM0Zi1kNzU4LTRkOTctYjg1YS1jM2IzMzQ5MmUxZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDI0NDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdiMjI3NDc0MTFmNDg5YjY1ZjA3OWI4NjcxZTA3M2U2ZjYyMGZkYTMxYWQwNzM2MGYwMjU1YTE2YzUxMWM0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.54q7vPViR7flGGNI-_SBsZLJ3pO8vLSv3rtfO6WZdE4)
> 
> ![image](https://private-user-images.githubusercontent.com/9602197/314513865-c6e46eef-3eed-43c8-977e-f110816e2318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODkzNzMsIm5iZiI6MTcxMDk4OTA3MywicGF0aCI6Ii85NjAyMTk3LzMxNDUxMzg2NS1jNmU0NmVlZi0zZWVkLTQzYzgtOTc3ZS1mMTEwODE2ZTIzMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDI0NDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQwZmIwOGFmOTM5MjVlNzBiYmQ4MDI4MDYxNmRlYjhiNDI4ZmQxZDM0MjZjODliMDFkNmUxMWM4NzE2MGJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LzR4mxNI3ZhXsYQDYNdEKcu4h-gdzeP7QTRBoJ8223c)
> 
> ![image](https://private-user-images.githubusercontent.com/9602197/314514051-6217fe7e-74d1-48f5-abb0-b23cbab8bd39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODkzNzMsIm5iZiI6MTcxMDk4OTA3MywicGF0aCI6Ii85NjAyMTk3LzMxNDUxNDA1MS02MjE3ZmU3ZS03NGQxLTQ4ZjUtYWJiMC1iMjNjYmFiOGJkMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDI0NDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI3ZjlhOGE3ODY1YjRiYzZlNDQ2YzM4NTJiMjMxMTcxMDI2ZTRjZjcwZDc1YmNjOWYyNzIyMDBiOTQyNWYwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.coW-WaALTjGM5hRYlTiaNyefgQcWzesajduEJZfOTq8)

我再试试

**Comment by jonfoo86** [comment]
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/6650602c-5dae-463b-9b74-0a54267868d3)

这个是我用两个浏览器的分别登录 cpp1 和 admin 的截图 ，正常

![image](https://github.com/gotoeasy/glogcenter/assets/17876826/bb43537e-5823-4cd3-9664-ea9c14c709a2)
这个是修改权限后的两个浏览器结果 ，不正常

这会库里面只有cpp1 和 cpp2系统的数据


然后我再插入eshadow 系统的数据，权限又好了

**Comment by gotoeasy** [comment]
确实！很好！
是性能优化步骤中没有测试到的一个非常隐蔽的权限问题，`0.14.2`版本中修复

**Comment by jonfoo86** [comment]
> 确实！很好！ 是性能优化步骤中没有测试到的一个非常隐蔽的权限问题，`0.14.2`版本中修复

感谢修复 ，期待中...

**Comment by jonfoo86** [comment]
> > 确实！很好！ 是性能优化步骤中没有测试到的一个非常隐蔽的权限问题，`0.14.2`版本中修复
> 
> 感谢修复 ，期待中...

已经修复了 6666
