### ISSUE TITLE
自己编译的服务没显示用户

### ISSUE THREAD

**Issue by jonfoo86** [gotoeasy/glogcenter#33]
就我问题多，见谅， 另外我昨天自己编译了一个服务器，发现管理员账户没显示用户列表 ，但是请求有数据

![image](https://github.com/gotoeasy/glogcenter/assets/17876826/9d99a02d-5fbb-4cef-8e54-33703d07b300)

另外就是自己编译的代码查询界面也有异常 
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/c1429b0a-74c2-4b43-bb09-b61167c066ba)

我是不是编译姿势不对 ？

**Comment by gotoeasy** [comment]
第一个问题，看你截图，实际页面上是显示了“2条数据”，不过是布局不对没有指定显示列（各种什么原因在客户端找不到配置），你按右上角配置图标，重置布局就行


第二个问题，是不是你把窗口拉太小了引起换行？小窗口或手机宽度不够时查看日志其实非常不方便，目前日志中心没有考虑支持这种场景（除非有比较合适的展示方式）

**Comment by jonfoo86** [comment]
第一个问题 我操作下这个按钮就好了：
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/321b62e8-1fe3-473f-bc76-8417212c66fd)

第二个还没解决 ，不过不重要

**Comment by jonfoo86** [comment]
感谢

**Comment by 007yourfriend** [comment]
我自己编译的服务器，怎么没有登录页面和用户信息列表页面呢？

**Comment by 007yourfriend** [comment]
我自己编译的服务器，怎么没有登录页面和用户信息列表页面呢？
源码中有login和glc/sysuser
<img width="956" alt="首页" src="https://github.com/user-attachments/assets/2d053c3e-a13f-4313-a25e-994eacfac8ad">

**Comment by gotoeasy** [comment]
看readme，问助手
