### ISSUE TITLE
glc  stop 不生效问题

### ISSUE THREAD

**Issue by jonfoo86** [gotoeasy/glogcenter#34]
![image](https://github.com/gotoeasy/glogcenter/assets/17876826/774aebbe-5a48-4015-bf7f-bb5dadba9505)

当服务已经起来的时候 ， 然后我想停止服务 ， ./glc stop ，然后其实是走不到kill 逻辑部分的 因为之前判断了端口， 因为端口在所有直接退出了 ./glc

**Comment by gotoeasy** [comment]
有道理，代码更新，下个版本时再发布

**Comment by gotoeasy** [comment]
v0.15.0 已修复
