### ISSUE TITLE
【定位相邻检索】搜索结果中，能否选择某一条记录，展示此条日志的前后n条记录显示

### ISSUE THREAD

**Issue by Autuan** [gotoeasy/glogcenter#35]
搜索结果中，能否选择某一条记录，展示此条日志的前后n条记录显示

在实际中，有时会需要查看某一条日志前后所有日志详情以辅助定位

**Comment by gotoeasy** [comment]
意思明白，也确实有这种需要，但页面上怎么简便操作好呢？
（已有检索条件影响怎么处理，已检索结果中某条的后n条日志很可能是不同系统的无关日志）

**Comment by Autuan** [comment]
> 意思明白，也确实有这种需要，但页面上怎么简便操作好呢？ （已有检索条件影响怎么处理，已检索结果中某条的后n条日志很可能是不同系统的无关日志）

可惜本人对 go 语言不甚熟悉，不能对这个项目做出代码上的贡献。 T-T

我原有一个很简单的想法：
查看前后信息时清除原有检索条件，重设检索条件时间范围为该条日志的前后几分钟 便可以展示目标日志的前后若干记录了

但同时，我并没有考虑到有可能会有不同系统的无关日志这种情况

**Comment by gotoeasy** [comment]
重置条件重新检索

1，保留日志仓条件（或是定为所选日志所属的日志仓）
2，系统条件定为所选日志所属的系统
3，时间条件考虑加以限制（前后n分钟），或是检索件数限制
4，其他条件清空（页面条件清空呢还是留着单纯显示避免又要再次输入）

还一个页面操作展示
添加操作列用小图标之类，向后查n件/向前查n件/前后各n件，查完是不是还得滚动到合适位置好（这挺难）


待都想好后再动手了

**Comment by gotoeasy** [comment]
`v0.15.0` 已发布，首版`定位相邻检索`功能大体如下，往后根据使用情况再继续改善 

1，分往常的`普通检索`，以及新增的`定位相邻检索`，`定位相邻检索`时检索按钮是警示颜色，`重置`按钮变为`取消`用以切换回`普通检索`模式
2，点日志行的`定位相邻检索`按钮时进入`定位相邻检索`模式，所点日志作为定位行总是黄色背景显示，同时查出前后的日志（推测是向哪个方向查看日志，该方向所查日志就查取更多些）
3，`定位相邻检索`时日志仓和系统是固定不可修改的查询条件，除了有相邻的查询规则外，其他条件的查询方式保持不变，用以按习惯进行筛选
4，`定位相邻检索`没有滚动查询的动作，想不断往后就不断的点选后面日志进行相邻检索，用意主要也是区别于`普通检索`
5，每次查取最大件数多少才合适目前很难确定，暂时保持和普通检索的一样，其他就是禁用自动检索、底部提示等细节的一些修改
