### ISSUE TITLE
能不能把环境变量改为配置文件配置呢

### ISSUE THREAD

**Issue by cnwangfei** [gotoeasy/glogcenter#37]

**Comment by gotoeasy** [comment]
众多场景综合使用下来，环境变量方式是最合适的

如果是因为适应命令行方式，感觉配置太多或者不便记忆等等，完全可以通过 docker-compose.yml 方式启动，docker-compose.yml 就是形同配置文件了

**Comment by cnwangfei** [comment]
在windows系统使用就不太方便了。

**Comment by gotoeasy** [comment]
windows系统上docker-compose不能用？
使用配置文件的话，docker命令映射配置文件启动，那多累，还不如写个bat文件双击就启动，bat里设定环境变量就好了
