### ISSUE TITLE
我有多个系统，每个系统下面还会对日志进行分类，能不能在日志中增加二级系统，查询日志时能指定查询某一个二级系统

### ISSUE THREAD

**Issue by cnwangfei** [gotoeasy/glogcenter#39]
系统     | 功能日志
-------- | -----
系统1  | A功能<br>B功能<br>C功能
系统2 | A功能<br>B功能<br>C功能<br>D功能

**Comment by gotoeasy** [comment]
你的意思是希望日志增加一个属性字段用于存放区分功能模块？

虽然加起来简单，不过一旦开了这个口，增加多少个属性字段才是个头，得有个好方案

**Comment by cnwangfei** [comment]
> 你的意思是希望日志增加一个属性字段用于存放区分功能模块？
> 
> 虽然加起来简单，不过一旦开了这个口，增加多少个属性字段才是个头，得有个好方案

就是这个意思

**Comment by gotoeasy** [comment]
这个至少需要前端自定义检索结果的表头标题，有个好方案后再考虑实现了

**Comment by gotoeasy** [comment]
暂且关闭，需求呼声多时再考虑
