### ISSUE TITLE
期望可以更改暴露的端口

### ISSUE THREAD

**Issue by JL-Code** [gotoeasy/glogcenter#40]
![image](https://github.com/gotoeasy/glogcenter/assets/14163944/ad89a650-8fd0-4ca0-9a7a-3b610f40ac1d)

**Comment by gotoeasy** [comment]
你这是自己调试的吧，修改前端配置文件 `.env`

**Comment by JL-Code** [comment]
> 你这是自己调试的吧，修改前端配置文件 `.env`

是的，这是我使用你的镜像跑的本地。看来我得自己修改前端.env 然后自行打一个镜像来使用。

**Comment by JL-Code** [comment]
> 你这是自己调试的吧，修改前端配置文件 `.env`

看了一下 .env， 我明白了，非127.0.0.1和localhost时会直接使用域名作为API访问域名，线上环境不用担心8080端口被占用了。
