### ISSUE TITLE
能否支持，查询系统名称列表

### ISSUE THREAD

**Issue by tianhuo3652** [gotoeasy/glogcenter#42]
大佬，![image](https://github.com/gotoeasy/glogcenter/assets/42002859/4738ff92-62fc-4589-aa91-7c095453f220)
系统名称是有多个的，但下拉框无法展示全部的分类，未开启账号登录

**Comment by gotoeasy** [comment]
目前的逻辑是这样：
查到的日志所属的系统，会放到列表中，所以一开始可能空白
空白时，也可以手动输入后回车，相当于列表中手动加了一个
如果开启了登录，且指定账号设定了系统名时，会自动填写


当前这个确实有点点不够方便，由于日志量大，每接收到一条日志就取出系统名来保存，感觉不优雅所以一直也没优化这个

还是要想想什么样的方式更好，想好后再改进

**Comment by tianhuo3652** [comment]
谢谢大佬的耐心解答，万分感谢
