### ISSUE TITLE
我想使用nginx配置一个二级目录来反向代理这个日志服务，但是配置不奏效

### ISSUE THREAD

**Issue by G-lin** [gotoeasy/glogcenter#44]
# 配置如下
location ^~ /glogcenter/ {
    keepalive_timeout 120s;
    proxy_pass http://localhost:8088/;
}

**Comment by gotoeasy** [comment]
0.15.2版本增加支持

配置例子：

```sh
location /glc {
  proxy_pass http://127.0.0.1:8080;
}
```

**Comment by G-lin** [comment]
> 0.15.2版本增加支持
> 
> 配置例子：
> 
> ```shell
> location /glc {
>   proxy_pass http://127.0.0.1:8080;
> }
> ```

很棒，哈哈，要是可以自定义就更好了。

**Comment by G-lin** [comment]
> glc



> 字样自定义也许可以
> 
> ```
> location /abcd/ {
>   proxy_pass http://127.0.0.1:8080/glc/;
> }
> ```

这个不行

**Comment by gotoeasy** [comment]
确实，api使用了glc目录，没有特别意义也，不想折腾这个，有兴趣的话就自己修改吧

**Comment by G-lin** [comment]
> > 0.15.2版本增加支持
> > 配置例子：
> > ```shell
> > location /glc {
> >   proxy_pass http://127.0.0.1:8080;
> > }
> > ```
> 
> 很棒，哈哈，要是可以自定义就更好了。
刚刚试了一下，这个配置好像也有问题，如没有登录的会自动跳到 根目录下的login，然后在刷新就404了

**Comment by gotoeasy** [comment]
有道理，前端路由漏修改，删除本地镜像后重新拉去吧
