### ISSUE TITLE
docker logging dirver怎么使用？

### ISSUE THREAD

**Issue by molixiaoge** [gotoeasy/glogcenter#45]
在不改变代码的情况，程序都是运行在docker容器里的，如何设置logging dirver 保存日志？

**Comment by gotoeasy** [comment]
docker容器中程序产生的日志，如何零侵入的收集到GLC，是这个意思吗？

理论上是可行的，docker配置为容器日志以json格式输出到文件，然后就是读文件内容传给GLC了
缺点1，docker环境要配置（代码无侵入，但docker环境有侵入）
缺点2，读文件内容传给GLC需要另外写程序
缺点3，日志的格式没那么人性化（比如区分出系统、IP、追踪码等并不都那么容易）

**Comment by molixiaoge** [comment]
是的，记录docker 容器产生的日志。
读文件方式，需要写额外的程序。我看了logging driver的设置是有一系列协议，比如fluentd ,syslog 等，是否可以通过http api的方式直接支持 logging driver呢？

**Comment by gotoeasy** [comment]
以日志驱动方式，直接输出到http目标服务地址？或许也是可以
可能像以下这样？没试过

``` sh
docker run -d \
  --log-driver=loki \
  --log-opt loki-url=http://localhost:3000/logs \
  <CONTAINER_IMAGE>  这样是否可以
```

**Comment by molixiaoge** [comment]
试了一下命令
docker run  --log-driver=loki  --log-opt loki-url=http://192.168.56.102:8080/glc/v1/log/add  nginx
提示  
![图片](https://github.com/gotoeasy/glogcenter/assets/1323533/d8ae58a8-a90a-4c6b-9072-ce07dd4e88ed)
docker run  --log-driver=loki  --log-opt loki-url=http://192.168.56.102:3000/logs  nginx
生成了很多随机日志

**Comment by molixiaoge** [comment]
![图片](https://github.com/gotoeasy/glogcenter/assets/1323533/53a8f198-6b06-4bd7-aba4-84778b997ec3)

**Comment by gotoeasy** [comment]
页面上闪电图标按钮点击生成的测试数据吧

**Comment by molixiaoge** [comment]
是点了闪电按钮了，目前安装了loki插件，提示参数错误

**Comment by gotoeasy** [comment]
我没用过哦，觉得格式化效果不好所以一直没试。若是部署或运维他人写的程序，确实也是方便

一步步怎么安装使用的过程，包括必要的配置文件等，可以都列出来
看看日志驱动、日志格式、发送日志等是否正确

**Comment by molixiaoge** [comment]
后期能支持一下,docker logging driver么？部署节点很方便

**Comment by gotoeasy** [comment]
容器日志的自动收集支持，这个看时间，也看需求呼声多少

**Comment by gotoeasy** [comment]
暂且关闭，需求呼声多时再考虑

**Comment by gotoeasy** [comment]
`0.17.0`版本开始，支持基于`fluentd` 收集各种日志，包括docker容器日志

**Comment by molixiaoge** [comment]
好的，感谢。
