### ISSUE TITLE
索引的创建速度跟什么有关系？

### ISSUE THREAD

**Issue by Zvli** [gotoeasy/glogcenter#46]
手工抛了1亿条日志数据，但是一天下来，索引只创建了2600w条左右

**Comment by gotoeasy** [comment]
主要是CPU和磁盘，设计考虑是优先响应保存好日志，空闲时才创建索引

**Comment by gotoeasy** [comment]
> 磁盘的IO吗？

对，磁盘IO影响数据存取速度
CPU核数影响日志计算处理速度
