### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Davis966** [gotoeasy/glogcenter#48]
login接口返回403

**Comment by gotoeasy** [comment]
检查下是否配置了黑名单缘故引起？
登录接口返回403只有这种情况
![image](https://github.com/user-attachments/assets/9be23eff-f913-4481-a0c2-b002fcf4bfcb)

https://glc.gotoeasy.top/ 也可试下，临时部署成需要登录
用户 glc
密码 GLogCenter100%666

**Comment by Davis966** [comment]
感谢，原因是我没看清楚注释，GLC_BLACK_LIST 这个配置去掉就可以了




加而不减
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gotoeasy/glogcenter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月10日(星期二) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gotoeasy/glogcenter] 登录失败 (Issue #48)





 
检查下是否配置了黑名单缘故引起？
 登录接口返回403只有这种情况
 image.png (view on web)
 
https://glc.gotoeasy.top/ 也可试下，临时部署成需要登录
 用户 glc
 密码 GLogCenter100%666
