### ISSUE TITLE
可不可以加一个按照时间节点去找日志

### ISSUE THREAD

**Issue by uouuou** [gotoeasy/glogcenter#5]
如题，现在都是关键字的日志查找方式，能不能加一个时间点的查找方式呢？有点没看懂您的代码逻辑，没找到该怎么修订没法PR

**Comment by uouuou** [comment]
是的，存在这样的需求可能性，但是我看了一下您的代码查询的时候是去寻找关键字时间不在关键字内部，而且还建议把所有的system做一个列表可以使用接口直接选择而不是现在这样做成一个关键字输入，还是有点浪费关键词搜索资源的

**Comment by gotoeasy** [comment]
总体的方向还是搜索引擎一样的简洁思路，不会考虑多字段条件分别输入进行检索

但时间范围不同于通常的关键字，是需要单独加输入范围条件的

**Comment by uouuou** [comment]
明白这个逻辑了，就是这块代码部分没看懂，引擎那边有点复杂了没法提交pr，抱歉

**Comment by gotoeasy** [comment]
0.8.8 版本已支持时间范围检索

**Comment by uouuou** [comment]
感谢老哥，我学习一下！
