### ISSUE TITLE
微服务整合后报错

### ISSUE THREAD

**Issue by Davis966** [gotoeasy/glogcenter#50]
奇怪的是gateway一样的配置方法可以启动成功，并且日志收集也没问题，其他微服务启动就报错。报错内容：Connected to the target VM, address: '127.0.0.1:53810', transport: 'socket'
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.model.processor.AppenderModelHandler - Could not create an Appender of type [top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender
ERROR in ch.qos.logback.core.model.processor.DefaultProcessor@fdf90612 - Failed to traverse model appender ch.qos.logback.core.model.processor.ModelHandlerException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender
ERROR in ch.qos.logback.core.model.processor.AppenderModelHandler - Could not create an Appender of type [top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender
ERROR in ch.qos.logback.core.model.processor.DefaultProcessor@fdf90612 - Failed to traverse model appender ch.qos.logback.core.model.processor.ModelHandlerException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender
<img width="602" alt="1726667033168" src="https://github.com/user-attachments/assets/a2d54832-820c-41b9-87fd-469de6a53812">

**Comment by gotoeasy** [comment]
别漏了依赖包哦

```xml
<!-- pom坐标 -->
<dependency>
    <groupId>top.gotoeasy</groupId>
    <artifactId>glc-logback-appender</artifactId>
    <version>0.17.1</version>
</dependency>
```

**Comment by Davis966** [comment]
<img width="480" alt="1726711089093" src="https://github.com/user-attachments/assets/831cf0b0-9b92-4db6-b935-a28132507991">jar包是有引入的

**Comment by gotoeasy** [comment]
我的理解，这个日志的意思就是

1，Logback 配置有错误，导致初始化失败
2，top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender 实例创建失败了，代码中是否能引入GlcHttpJsonAppender这个类呢（确认真的配好了依赖包）？ 

你可以试试最简单的配置例子（去除多余配置，看是不是哪里写错了影响）

```xml
<!-- 一个简单的logback-spring.xml配置例子 -->
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">
    <appender name="CONSOLE"
        class="ch.qos.logback.core.ConsoleAppender">
        <Target>System.out</Target>
        <encoder>
            <pattern>%d-%c-%t-%5p: %m%n</pattern>
        </encoder>
    </appender>

    <appender name="GLC" class="top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender">
        <glcApiUrl>http://127.0.0.1:8080/glc/v1/log/add</glcApiUrl>
        <system>demo</system>
        <layout>
            <pattern><![CDATA[%m %n]]></pattern>
        </layout>
    </appender>

    <root level="DEBUG">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="GLC" />
    </root>
</configuration>
```

**Comment by Davis966** [comment]
是我这边的问题，我把 .idea目录删除，重新导入项目就不报错了
