### ISSUE TITLE
搜索内容不对

### ISSUE THREAD

**Issue by molixiaoge** [gotoeasy/glogcenter#51]
开启nginx容器做fluentd转发到glogcenter简单测试，发现日志都可以转发到glogcenter上，并且展示的条目是19条，查看容器一共打印19条，说明fluentd转发没问题。

![图片](https://github.com/user-attachments/assets/efbe1456-af6b-420f-8962-54228aed5a24)

但是通过搜索框搜索，发现条目数对不上，只有17条

![图片](https://github.com/user-attachments/assets/6492d452-2ce8-4eb6-a97e-b3f395fd745d)

通过系统名过滤，也不对，只有16条

![图片](https://github.com/user-attachments/assets/c9d56ecb-e751-4715-ab20-385f9e531af9)

查看索引，发现全部建立了索引

![图片](https://github.com/user-attachments/assets/b1b4150b-49b5-4464-ae26-e81c8e60139f)

fluentd只做了如下更改

```
<filter *>
  @type record_transformer
  enable_ruby
  <record>
    loglevel ${case record["log"] when / info /i then "INFO" when / warn /i then "WARN" when / error /i then "ERROR" else "DEBUG" end}
    text ${record["log"]}
    system ${record["container_name"].gsub("/", "")}
    # system ${record["container_name"].split('.').first.gsub("/", "")}  
    # serverip ${"127.0.0.1"}
    date ${case record["log"] when /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} / then record["log"].match(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} /)[0] else time.strftime('%Y-%m-%d %H:%M:%S.%3N') end}
    # system ${"glogcenter"}
  </record>
  remove_keys container_id,container_name,source,log
</filter>
```

**Comment by gotoeasy** [comment]
通常是因为索引还没有建好的原因，无条件检索时直接取数据，带条件检索时只查索引

程序优先响应保存日志数据，闲时才建索引
如果日志并发量大，机器硬盘CPU跟不上，极端情况下会一直都在处理保存数据，导致最终带条件检索几乎查不到新日志

**Comment by molixiaoge** [comment]
索引页面，查看已经全部建立好了

**Comment by gotoeasy** [comment]
这就费解了，难道是断电影响？
我试了下，这个系统名字符串形式是允许的，分词也是稳定的

![image](https://github.com/user-attachments/assets/4caad865-3127-4a95-bf3a-e06f7c39acd3)

为啥你那里系统名索引少了3条，关键词`4y1fzhyrjekgq004reojirpwd`索引少了2条，呵呵...

**Comment by molixiaoge** [comment]
测试新数据的时候没有断电，但是之前应该有直接关机过。

**Comment by gotoeasy** [comment]
> 测试新数据的时候没有断电，但是之前应该有直接关机过。

也许是这个原因，一条日志有多个关键词，不同关键词索引的保存没有数据库那样的事务保证

**Comment by molixiaoge** [comment]
在测试这19条数据的时候没有关机，也会因为之前关机导致搜索有问题么？

**Comment by gotoeasy** [comment]
> 在测试这19条数据的时候没有关机，也会因为之前关机导致搜索有问题么？

不会

但我想不出会有什么原因影响了

**Comment by gotoeasy** [comment]
1，建索引的影响，已排除
1，分词结果不同的影响，可能性极低
2，存盘的影响，正常使用的话，可能性极低

`还有谁`

**Comment by gotoeasy** [comment]
`那谁`应该是索引问题， `v0.17.2`修复

**Comment by molixiaoge** [comment]
好

**Comment by molixiaoge** [comment]
搜索内容，格式是时间，返回的值不对

![图片](https://github.com/user-attachments/assets/7ea1985b-3568-4a53-bbbf-296cf02696b2)

**Comment by gotoeasy** [comment]
这是关键词检索，不是精确检索

关键词检索是把输入的条件会分词，然后匹配关键词，检索条件中每个关键词都包含的日志筛选出来显示

**Comment by molixiaoge** [comment]
那如何精确搜索

**Comment by gotoeasy** [comment]
> 那如何精确搜索

巨量数据下，没有任何一个搜索引擎会去考虑支持精确搜索

看截图你想按日志的时间搜索，你应该把日志的时间转成GLC的时间格式后存入时间字段，然后就能用时间范围进行搜索

**Comment by molixiaoge** [comment]
好的

**Comment by molixiaoge** [comment]
日志量过大，搜索出来后，定位相邻检索，会出现超时无法定位

![图片](https://github.com/user-attachments/assets/dec1d234-964b-47ea-99fe-89aedd036380)

**Comment by gotoeasy** [comment]
点定位相邻检索出现超时错误的意思？原因很多，不好乱猜，日志量大并不是重要原因

**Comment by molixiaoge** [comment]
就是不展示结果，提示 time exceeded。

另外我把日志清了，再是相邻，看到的日志顺序和展示的不连续


展示页面
![图片](https://github.com/user-attachments/assets/ad8b2997-8eab-4e9e-9974-6126aa76c3f8)

相邻页面
![图片](https://github.com/user-attachments/assets/f0866f7b-37aa-467d-be42-f78225ab2ec8)


顺序和展示页面不一致。

**Comment by gotoeasy** [comment]
time exceeded 就是请求超时了吧，能请求出来时，检索显示多长时间，不能检索出来或是检索很慢的时候，网络如何？机器性能监控看看是什么情况？瓶颈要找出来才行。运行环境或硬件配置不同会有不同的瓶颈，如果怀疑数据量大或并发量的大影响，建议提高硬件配置，主要是磁盘IO和CPU

顺序问题，为什么你截图上查询的结果不一样，一个有ERROR日志，一个没有？展示页是不是有检索条件？
截图中，相同的几条日志，顺序是一样的
![image](https://github.com/user-attachments/assets/9c8f2e54-b90d-49cd-a493-fd9822669547)

**Comment by gotoeasy** [comment]
1万条日志数据和10亿条日志数据，检索时并不会有什么明显耗时差异，通常性能影响最大的是磁盘IO，并发大的话也看CPU，内存占用不大一般足够

**Comment by molixiaoge** [comment]
排除数据量大的原因已经清空重启过容器，展示页重置过搜索条件并且刷新过页面。
我和容器日志对比过顺序和内容，展示页是对的，也就是说以展示页为准。
我的理解是我在搜索结果点击定位相邻，相邻的展示日志应该和展示页顺序内容一致的吧？

**Comment by gotoeasy** [comment]
截图的顺序不是对的嘛，我都箭头指出来了
页面显示顺序是按id从大到小排序，没有混乱的可能

相邻检索只有DEBUG数据，是因为DEBUG级别条件勾选了吧

【相邻检索】的意思是。。。。。不可能和普通检索一样，不然黄色警告干啥
相邻检索是查询指定日志的前后最紧挨的、满足相邻检索条件的数据，结果数据有一条黄色背景的就是你指定的位置，查出前后的都显示出来
普通检索是查满足条件的前N条


当你用各种关键词条件筛选，终于查到了你要找的一条日志，但是那条日志的前后上下文可能并不全，这时点相邻检索，就可疑具体的查看前后紧挨的相关日志了，也还可以进一步填写条件过滤数据。这是相邻检索使用的一种场景

**Comment by molixiaoge** [comment]
只有debug数据，日志级别没有勾选debug

**Comment by gotoeasy** [comment]
相邻检索只能看到DEBUG数据？难以理解，要么就是相邻的调速范围内都是DEBUG数据，再继续前后翻点相邻检索查更多的相邻数据看，或是加ERROR条件就能查出来

你若说普通检索能查到的数据，相邻检索却无法查到，那这个就不能理解了
要是这么怪异，那就重装大法，停止服务删除镜像重新拉取镜像重新部署重新映射新数据目录

**Comment by molixiaoge** [comment]
我理解下相邻搜索的意思，比如展示页面是
7
6
5
4
3
2
1

我查询4，并点击相邻展示，展示的结果应该是连续的吧
6
5
4
3
2


但是实际上相邻展示的结果是，这样的不连续的

6
4
3
2

**Comment by gotoeasy** [comment]
所以说重装大法

按你说的是缺了5的数据，相邻检索是有固定的系统条件，5的数据没有被正常生成系统关键词索引的话就会查不出来

**Comment by molixiaoge** [comment]
好的

**Comment by molixiaoge** [comment]
清理容器所有内容，docker全部清理，`gloc 版本0.17.2`
新建测试容器，容器应用全局加锁自增，从1开始输出，保证顺序一致，开启容器日志如下
测试代码main.go

```
package main

import (
	"sync"
	"sync/atomic"
	"time"

	"github.com/sirupsen/logrus"
)

var (
	counter int32 // 全局计数器
	lock    sync.Mutex
)

func main() {
	var wg sync.WaitGroup
	for i := 0; i <= 10000; i++ {
		wg.Add(1)

		go func() {

			defer wg.Done()

			for {
				lock.Lock()
				logrus.Info(atomic.AddInt32(&counter, 1))
				lock.Unlock()
				// fmt.Println(atomic.AddInt32(&counter, 1))
				time.Sleep(30 * time.Second)
			}
		}()
	}
	wg.Wait()
}

```

容器代码,dockerfile

```
FROM alpine
WORKDIR /app
COPY hello .
CMD ["./hello"]


```

日志列表，显示索引建立完成
![图片](https://github.com/user-attachments/assets/5c031f94-4706-4947-9d95-641bcbc0c2b4)

展示页面，关键字 msg=134750 ，顺序是一致的
![图片](https://github.com/user-attachments/assets/7e0a882d-53aa-48cf-a0a8-1d0eee237342)

搜索页面，关键字 msg=134750，可以搜索到
![图片](https://github.com/user-attachments/assets/96fd3224-3250-4b94-aa2b-65d67a8b6fd6)

定位相邻，顺序错乱
![图片](https://github.com/user-attachments/assets/3be17f34-57f6-4388-b23e-cdc1d1c66917)

**Comment by gotoeasy** [comment]
很好，很清晰
更新了 `gotoeasy/glc:latest` 可以拉取下试试，不要用旧数据避免混淆难确认

**Comment by molixiaoge** [comment]
latest  镜像对了
