### ISSUE TITLE
集群化，java使用logback应该如何配置？

### ISSUE THREAD

**Issue by tianhuo3652** [gotoeasy/glogcenter#55]
<appender name="GLC" class="top.gotoeasy.framework.glc.logback.appender.GlcHttpJsonAppender">
    <glcApiUrl>http://127.0.0.1:8080/</glcApiUrl> 
    <glcApiKey>X-GLC-AUTH:glogcenter</glcApiKey>  
    <system>demo</system>                         
    <layout>
        <pattern><![CDATA[%m %n]]></pattern>
    </layout>
</appender>
大佬，集群化glc，请问logback中地址，应该如何配置？

**Comment by gotoeasy** [comment]
发送到其中一台就行，集群内部会处理自动转发同步

**Comment by tianhuo3652** [comment]
请问，如果是三个服务器部署三个节点，日志数据，三台服务器日志数据 都会转发同步吗？

**Comment by gotoeasy** [comment]
> 请问，如果是三个服务器部署三个节点，日志数据，三台服务器日志数据 都会转发同步吗？

是的，发往其中任意一台，会同步自动转发到另2台，查询也可以查其中任意一台

但是，不过，机器网络也是复杂难控的，这只是一定程度上的高可用高可靠性的保障，但又不是金融系统那种极高要求的设计实现

**Comment by neowj** [comment]
如果有一台glc机器挂掉了，会影响正在运行的java服务吗

**Comment by gotoeasy** [comment]
java服务是你的应用，应用是否正常不受glc影响，应用发送日志到glc是只管发送不检查结果是否成功，glc集群服务全关闭也不会影响java应用的

**Comment by neowj** [comment]
明白了，如果不影响阻塞的话那就是不影响
