### ISSUE TITLE
是否可以增加logid列的显示

### ISSUE THREAD

**Issue by ChenDY2233** [gotoeasy/glogcenter#57]
* 在搜索页面，增加LOGID的显示，相较于时间，更直观的区分日志顺序

![PixPin_2024-11-28_17-30-17](https://github.com/user-attachments/assets/05d6c4f6-6fd3-4f69-bb77-1f7567d16a02)

**Comment by gotoeasy** [comment]
也行，空时加上

**Comment by ChenDY2233** [comment]
> 也行，空时加上，偶尔确认用也可以
> 
> 只是要注意，这id是不参与检索的，检索时不要想用id检索又检索不出来产生误解

logid是否可以添加设置项，可选延续上一日志仓的序列，而非每个日志仓都重新开始序列

**Comment by gotoeasy** [comment]
如果不重新开始序列，迟早会有溢出发生，logid说到底还是内部管理日志用途，外部不该去关注太多

**Comment by ChenDY2233** [comment]
好的明白

**Comment by gotoeasy** [comment]
`v0.17.3`已修改
