### ISSUE TITLE
timeout of 30000ms exceeded

### ISSUE THREAD

**Issue by tianhuo3652** [gotoeasy/glogcenter#59]
操作系统版本：UnionTech OS Server 20(统信)
目前出现的问题是 访问接口
/glc/v1/log/search
/glc/v1/store/list
要超过30秒才会有返回结果(postman请求)，但是，写入日志接口完全正常，数据量不大，日志只有29M
排查方向：
1.担心是集群化问题，单独在相同环境，新开一台服务器，相同操作系统，运行单节点，发现还是很慢，超过30秒
2.之前在现有环境部署，是没有任何问题的，已经运行了一周左右，昨天执行了以下操作：
   2.1升级到最新17.3版本，发现，启动日志服务，没有下面的日志输出
   2024/12/02 09:00:08 INFO 关闭WordIndexStorage： logdata-20241202/inverted/k
   2024/12/02 09:00:08 INFO 空闲等待接收日志
   2024/12/02 09:00:08 INFO 关闭LogDataStorage： logdata-20241202/data
   2024/12/02 09:00:50 INFO 关闭SysmntStorage： .sysmnt
    怀疑是打包有问题，然后版本回退到之前版本，重启服务之后，查询日志界面 就出现超时，后台没有错误日志，只是接口响应超过30s
3.本地运行访问是没有任何问题，访问一切正常，无论是原有版本，还是17.3版本，都没有问题
这是在 线上环境使用curl命令访问：服务器本机使用crul访问，也是很慢
![1733102204902](https://github.com/user-attachments/assets/751b1d70-eab2-4983-afb8-38c8c2186245)

请问大佬，现在应该朝哪个方向排查，  求助大佬，指明方向，现在是完全没有头绪了
![1733101475277](https://github.com/user-attachments/assets/35a98933-f41a-4830-a61a-6a75b13a734b)

**Comment by gotoeasy** [comment]
服务器负载什么状况？IO、CPU、内存
也许磁盘 IO 已经高负荷

**Comment by tianhuo3652** [comment]
找到问题了，因为是内网部署，网段是9.x.x.x 导致这里识别ip出问题，后续有内部部署的，需要注意一下这里
![1733117049492](https://github.com/user-attachments/assets/d3aefcbd-331e-42fa-9800-633468ffb3b0)
另外请问一下大佬，咱们现在生产环境glc日志输出，这里参数应该如何配置？是控制台输出 false 日志级别info？
![1733117191973](https://github.com/user-attachments/assets/2b98e4cf-8346-4de3-87fc-2b45f3e1d8e6)

**Comment by gotoeasy** [comment]
原来如此，开启了IP地址查询，但内网环境限制了外网访问，导致经常超时

**Comment by gotoeasy** [comment]
容器日志输出级别影响容器本身日志量，通常Info级别就可以了

控制台输出量过大的话也可能影响性能，必要时可以关闭

容器日志想看的话，也可以配置容器日志收集，统一查看
