### ISSUE TITLE
集群化日志转发问题

### ISSUE THREAD

**Issue by tianhuo3652** [gotoeasy/glogcenter#60]
大佬，目前情况是这样，服务器 10，11，12 集群化部署三个节点服务，在13上使nginx做了负载，
但是这样就会有一个问题，
日志会随机的写入10，11，12 ，导致在10通过网页查询日志，发现同一次请求的日志，看不全，
原因是 一次请求的日志，被随机写入到10，11，12节点，请教一下，这种情况有什么好的解决方式吗？
如何才能通过其中任意一个节点，都能查看一次请求，被分发到不同节点的日志数据

**Comment by gotoeasy** [comment]
1）日志写入任一节点，应该都会转发到其他节点，其他节点接收到转发的日志存好再生成好索引后，就都能按关键词检索出来，你说的“看不全”我不大理解

2）在13上使nginx做了负载，建议以其中一台为主，另两台为备机，用这种策略做负载均衡，能比较好的控制日志 ID 顺序，因为日志 ID 是单机递增的生成策略，没有使用集群全局生成的策略（影响性能）。
也就是写日志时以其中一台为主不变，查日志从任一台查询都可以，只有建索引速度有可能会影响到没能立即检索到新日志

**Comment by tianhuo3652** [comment]
我先按照2的方式，配置一下，看能否解决问题，谢谢大佬的耐心解答，万分感谢
