### ISSUE TITLE
前端各种报错，能否适用一下新版本？

### ISSUE THREAD

**Issue by 007yourfriend** [gotoeasy/glogcenter#61]
cd glc\www\web
npm run serve
由于版本问题，各种报错，能否适应一下新版本，或者在某个论坛回答一下呢
谢谢

**Comment by gotoeasy** [comment]
`pnpm i`
`npm run serve`
`npm run build`
`npm run preview`

都好好的哦

**Comment by 007yourfriend** [comment]
感谢您的回复，居然这么快，感谢！
我卸载了再重来一遍试试看

**Comment by 007yourfriend** [comment]
果然，最终成功了，感谢！
<img width="956" alt="首页" src="https://github.com/user-attachments/assets/9533bf9e-e551-44ef-84a8-6d9a67962175">
这个界面只能查看，没有登录界面（但源码下有login.vue）和配置选项（源码下有sysuser）

**Comment by gotoeasy** [comment]
。。。看readme，问助手

**Comment by 007yourfriend** [comment]
`GLC_ENABLE_LOGIN`是否开启用户密码登录功能，默认`false`

**Comment by 007yourfriend** [comment]
`GLC_ENABLE_LOGIN`是否开启用户密码登录功能，默认`false`
谢谢

**Comment by 007yourfriend** [comment]
closed
