### ISSUE TITLE
system不支持中文

### ISSUE THREAD

**Issue by uouuou** [gotoeasy/glogcenter#8]
如题，我看了一下是存储的时候存储桶将全部都分词了，这里system可否做成可选择分词，也可不分词的模式呢？毕竟中文在系统过多的时候还是有用的

**Comment by gotoeasy** [comment]
扩大场景的话，当然，作成可选择system进行筛选查询会好些，这个可能0.9版本再考虑了


system我一般都是使用英文或英文缩写，也就是分词或不分词结果都是一个词，这样使用可以减少使用问题

system即使可选为不分词，还是有一定问题的
比如【system=管理系统】，如果只想查询这个system，输入【管理系统】并不一定是只筛选到这个系统，可能也会包含满足这个关键词的其他system日志，这样的结果是比较迷惑的

**Comment by uouuou** [comment]
> 扩大场景的话，当然，作成可选择system进行筛选查询会好些，这个可能0.9版本再考虑了
> 
> system我一般都是使用英文或英文缩写，也就是分词或不分词结果都是一个词，这样使用可以减少使用问题
> 
> system即使可选为不分词，还是有一定问题的 比如【system=管理系统】，如果只想查询这个system，输入【管理系统】并不一定是只筛选到这个系统，可能也会包含满足这个关键词的其他system日志，这样的结果是比较迷惑的

这个确实是存在您说的问题，要么就是做一个system列表去选择，要么就是做成索引，我现在是在日志里面加了当前系统的中文名字然后将系统名字修改为中文也能搜索就是会导致您上面说的，=系统名字相似的时候会一起带出

**Comment by uouuou** [comment]
哈哈，那我必须更新一下了，感谢大佬解决！

**Comment by gotoeasy** [comment]
这个目前只是简易实现，操作性一般
以后再改进了
